server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: astronomy-service
astro:
  catalog:
    naked-eye:
      manifest-location: classpath:catalogs/naked-eye/manifest.json
      asset-location: classpath:catalogs/naked-eye/catalog.json.gz
    sky-content:
      manifest-location: classpath:catalogs/sky-content/manifest.json
      asset-location: classpath:catalogs/sky-content/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
