/**
 * Browsable surface panoramas, one or more per landing site.
 *
 * GENERATED by `tools/moon-textures/moon_panoramas.py` - edit the manifest there, not this
 * file. Each entry carries the geometry the viewer needs: the azimuth the centre of the
 * image faces and the azimuth span it covers, both degrees clockwise from selenographic
 * north, plus the vertical field of view of the frame.
 *
 * `headingDeg` is 0 until the source frames' own headings are recovered from the Apollo
 * Image Atlas. A zero heading means the placement is unverified and the viewer says so
 * rather than implying the panorama is oriented correctly.
 */

export interface MoonPanorama {
  id: string
  siteId: string
  title: string
  caption: string
  /** Path under the public directory. */
  file: string
  width: number
  height: number
  /** Azimuth of the image centre, degrees clockwise from north. 0 = unverified. */
  headingDeg: number
  /** Azimuth span covered by the image, in degrees. 360 means it closes. */
  spanDeg: number
  /** How `spanDeg` is known: 'documented', 'closes', or 'modelled'. */
  spanSource: 'documented' | 'closes' | 'modelled'
  /** Vertical field of view of the frame, in degrees. */
  verticalFovDeg: number
  /** Source frames the stitch was built from. */
  sourceFrames: string
  credit: string
  licence: string
}

export const MOON_PANORAMAS: MoonPanorama[] = [
  {
    id: "apollo-11-tranquility-base",
    siteId: "apollo-11",
    title: "Tranquility Base, looking south-west",
    caption: "Apollo 11, 20 July 1969. Photographed from about ten metres west of the Lunar Module \"Eagle\"'s plus-Z footpad, looking toward the south-west at the crater rim Armstrong had spotted from the window during the descent.",
    file: "/demos/moon/panoramas/apollo-11-tranquility-base.webp",
    width: 5120,
    height: 394,
    headingDeg: 0,
    spanDeg: 160,
    spanSource: "modelled",
    verticalFovDeg: 21.55,
    sourceFrames: "magazine 40, frames AS11-40-5881 to 5891 (11 frames)",
    credit: "NASA / Johnson Space Center (jsc2007e045375)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-11-armstrong-crater",
    siteId: "apollo-11",
    title: "Armstrong's crater from Tranquility Base",
    caption: "Apollo 11, 20 July 1969. A crater Armstrong called out during the descent, with the Lunar Module and flag at the left edge and the photographer's own shadow at the right.",
    file: "/demos/moon/panoramas/apollo-11-armstrong-crater.webp",
    width: 5120,
    height: 1461,
    headingDeg: 0,
    spanDeg: 130,
    spanSource: "documented",
    verticalFovDeg: 64.90,
    sourceFrames: "magazine 40, frames AS11-40-5954 to 5961 (8 frames)",
    credit: "NASA / Johnson Space Center (jsc2008e040725)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-12-surveyor-crater",
    siteId: "apollo-12",
    title: "Surveyor Crater from the rim",
    caption: "Apollo 12, November 1969. Taken from north-east of Intrepid, sweeping west past the flag and then round into Surveyor Crater, where Surveyor 3 had landed two and a half years earlier.",
    file: "/demos/moon/panoramas/apollo-12-surveyor-crater.webp",
    width: 5120,
    height: 603,
    headingDeg: 0,
    spanDeg: 280,
    spanSource: "modelled",
    verticalFovDeg: 57.69,
    sourceFrames: "magazine 47, frames AS12-47-6982 to 7006 (25 frames)",
    credit: "NASA / Johnson Space Center (jsc2007e045376)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-14-fra-mauro",
    siteId: "apollo-14",
    title: "Toward the western horizon",
    caption: "Apollo 14, February 1971. A sweep across the Fra Mauro formation toward the western horizon, from the terrain Shepard and Mitchell crossed on foot.",
    file: "/demos/moon/panoramas/apollo-14-fra-mauro.webp",
    width: 5120,
    height: 614,
    headingDeg: 0,
    spanDeg: 300,
    spanSource: "modelled",
    verticalFovDeg: 63.00,
    sourceFrames: "magazine 66, frames AS14-66-9271 to 9293 (23 frames)",
    credit: "NASA / Johnson Space Center (jsc2007e045377)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-15-hadley-rille",
    siteId: "apollo-15",
    title: "Hadley Rille and the Lunar Roving Vehicle",
    caption: "Apollo 15, August 1971. David Scott at the Lunar Roving Vehicle on the edge of Hadley Rille, photographed by James Irwin south of Station 2.",
    file: "/demos/moon/panoramas/apollo-15-hadley-rille.webp",
    width: 5120,
    height: 1774,
    headingDeg: 0,
    spanDeg: 110,
    spanSource: "modelled",
    verticalFovDeg: 66.70,
    sourceFrames: "magazine 85, frames AS15-85-11448 to 11453 (6 frames)",
    credit: "NASA / Johnson Space Center (jsc2011e118359)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-16-station-1",
    siteId: "apollo-16",
    title: "Station 1, Descartes highlands",
    caption: "Apollo 16, April 1972. Charles Duke collecting samples at Station 1 while John Young photographs him, on the first moonwalk of the mission.",
    file: "/demos/moon/panoramas/apollo-16-station-1.webp",
    width: 5120,
    height: 531,
    headingDeg: 0,
    spanDeg: 260,
    spanSource: "modelled",
    verticalFovDeg: 47.20,
    sourceFrames: "magazine 114, frames AS16-114-18416 to 18431 (16 frames)",
    credit: "NASA / Johnson Space Center (jsc2012e052598)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-17-station-2",
    siteId: "apollo-17",
    title: "Station 2, Taurus-Littrow",
    caption: "Apollo 17, December 1972. The second moonwalk: the parked Lunar Roving Vehicle and astronaut footprints across the valley floor, with the South Massif ridge beyond.",
    file: "/demos/moon/panoramas/apollo-17-station-2.webp",
    width: 5120,
    height: 542,
    headingDeg: 0,
    spanDeg: 240,
    spanSource: "modelled",
    verticalFovDeg: 44.50,
    sourceFrames: "magazine 138, frames AS17-138-21053 to 21073 (21 frames)",
    credit: "NASA / Johnson Space Center (jsc2004e52777)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "apollo-17-station-5",
    siteId: "apollo-17",
    title: "Station 5, on the edge of Camelot",
    caption: "Apollo 17, December 1972. Boulders and the shoulder of the North Massif at Station 5, looking toward the massif. The strip covers most of the horizon but its two ends do not meet, so turning stops at the edge of the photograph.",
    file: "/demos/moon/panoramas/apollo-17-station-5.webp",
    width: 5120,
    height: 606,
    headingDeg: 0,
    spanDeg: 300,
    spanSource: "modelled",
    verticalFovDeg: 62.18,
    sourceFrames: "magazine 145, frames AS17-145-22159 to 22181 (23 frames)",
    credit: "NASA / Johnson Space Center (jsc2004e20304)",
    licence: "NASA imagery, public domain in the United States",
  },
  {
    id: "change-4-farside-lander",
    siteId: "change-4",
    title: "The far side of the Moon, from Chang'e 4",
    caption: "Chang'e 4, January 2019. The first panorama taken from the lunar far side: the lander's solar panels and the Yutu-2 rover's tracks inside Von Karman crater, in the South Pole-Aitken basin.",
    file: "/demos/moon/panoramas/change-4-farside-lander.webp",
    width: 5120,
    height: 629,
    headingDeg: 0,
    spanDeg: 300,
    spanSource: "modelled",
    verticalFovDeg: 64.52,
    sourceFrames: "lander terrain camera ring shot, released by CNSA via the IAU",
    credit: "CNSA / CLEP, via the International Astronomical Union (iau1901a)",
    licence: "CC BY 4.0",
  },
]

/** Every panorama published for a site, in manifest order. */
export function panoramasForSite(siteId: string): MoonPanorama[] {
  return MOON_PANORAMAS.filter((panorama) => panorama.siteId === siteId)
}

export function findPanorama(id: string): MoonPanorama | null {
  return MOON_PANORAMAS.find((panorama) => panorama.id === id) ?? null
}
