/**
 * High-resolution crops for each hotspot, exported from NASA's LROC WAC image service.
 *
 * Generated by the recipe in the demo's ATTRIBUTION.md; edit that, not this list. Each crop is
 * a lon/lat bounding box, so the runtime places it on the sphere without any guesswork: the
 * patch geometry follows the same convention as the global atlas, `u = (lon + 180) / 360` and
 * `v = (90 - lat) / 180`, and the image fills that box exactly.
 */

import { SITE_BUMP_SCALE } from './siteBumps'
import { SITE_RELIEF, type SiteRelief } from './siteRelief'

export interface MoonSite {
  id: string
  /** [west, south, east, north]; east passes 180 for a box crossing the antimeridian. */
  bbox: [number, number, number, number]
  width: number
  height: number
  /**
   * Hue multiplier that lines the grey crop up with the atlas: the crop's brightness already
   * matches, this only corrects the colour cast.
   */
  tint: [number, number, number]
}

/**
 * Where a crop sits in its feature's drill-down. Levels are shown in this order and each one
 * fades in once it covers the viewport on its own:
 *
 * - `wide`  a regional WAC crop, which is what the arrival flight is framed around;
 * - `fine`  the WAC crop the feature has always had, about ten times sharper;
 * - `nac`   an LROC Narrow Angle Camera mosaic over roughly 10-20 km;
 * - `nac-close` the same mosaic at its own pixel scale, one to six kilometres across.
 */
export type MoonSiteTier = 'wide' | 'fine' | 'nac' | 'nac-close'

const TIER_ORDER: MoonSiteTier[] = ['wide', 'fine', 'nac', 'nac-close']

/** Tier of a crop, which the id encodes: `<feature>`, `<feature>-wide`, `<feature>-nac`, ... */
export function siteTier(id: string): MoonSiteTier {
  if (id.endsWith('-nac-close')) return 'nac-close'
  if (id.endsWith('-nac')) return 'nac'
  if (id.endsWith('-wide')) return 'wide'
  return 'fine'
}

export const MOON_SITES: MoonSite[] = [
  {
    id: 'oceanus-procellarum',
    bbox: [-82.13615, -6.33615, -32.66385, 43.13615],
    width: 1536,
    height: 1536,
    tint: [1.0265, 1.0116, 0.9619],
  },
  {
    id: 'mare-imbrium',
    bbox: [-40.33615, 8.06385, 9.13615, 57.53615],
    width: 1536,
    height: 1536,
    tint: [1.0293, 1.0109, 0.9598],
  },
  {
    id: 'mare-ser-enitatis',
    bbox: [-7.23615, 3.26385, 42.23615, 52.73615],
    width: 1536,
    height: 1536,
    tint: [1.0276, 1.0104, 0.9619],
  },
  {
    id: 'mare-tranquillitatis',
    bbox: [6.66385, -16.23615, 56.13615, 33.23615],
    width: 1536,
    height: 1536,
    tint: [1.0213, 1.011, 0.9677],
  },
  {
    id: 'mare-crisium',
    bbox: [34.36385, -7.73615, 83.83615, 41.73615],
    width: 1536,
    height: 1536,
    tint: [1.0246, 1.0102, 0.9652],
  },
  {
    id: 'mare-orientale',
    bbox: [-117.53615, -44.13615, -68.06385, 5.33615],
    width: 1536,
    height: 1536,
    tint: [1.017, 1.0097, 0.9732],
  },
  {
    id: 'south-pole-aitken',
    bbox: [-179.7, -77.74, -130.22, -28.26],
    width: 1536,
    height: 1536,
    tint: [1.0308, 1.0093, 0.9599],
  },
  {
    id: 'tycho',
    bbox: [-15.56515, -47.51515, -7.15485, -39.10485],
    width: 1536,
    height: 1536,
    tint: [1.0078, 1.0093, 0.9829],
  },
  {
    id: 'copernicus',
    bbox: [-24.68092, 5.01908, -15.47908, 14.22092],
    width: 1536,
    height: 1536,
    tint: [1.0121, 1.0119, 0.976],
  },
  {
    id: 'aristarchus',
    bbox: [-49.37889, 21.72111, -45.42111, 25.67889],
    width: 1199,
    height: 1199,
    tint: [1.006, 1.0136, 0.9804],
  },
  {
    id: 'clavius',
    bbox: [-25.8281, -69.8281, -2.9719, -46.9719],
    width: 1536,
    height: 1536,
    tint: [1.0099, 1.0104, 0.9797],
  },
  {
    id: 'tsiolkovskiy',
    bbox: [119.8671, -29.4829, 138.0729, -11.2771],
    width: 1536,
    height: 1536,
    tint: [1.0193, 1.0112, 0.9695],
  },
  {
    id: 'shackleton',
    bbox: [-180.0, -90.0, 180.0, -87.92111],
    width: 2048,
    height: 1024,
    tint: [1.0175, 1.0095, 0.973],
  },
  {
    id: 'apollo-11',
    bbox: [17.49632, -5.24868, 29.36968, 6.62468],
    width: 1536,
    height: 1536,
    tint: [1.0079, 1.0132, 0.9789],
  },
  {
    id: 'apollo-17',
    bbox: [24.83332, 14.25332, 36.70668, 26.12668],
    width: 1536,
    height: 1536,
    tint: [1.0215, 1.0132, 0.9653],
  },
  {
    id: 'change-3',
    bbox: [-25.44868, 38.18432, -13.57532, 50.05768],
    width: 1536,
    height: 1536,
    tint: [1.0409, 1.0116, 0.9475],
  },
  {
    id: 'change-4',
    bbox: [174.7, -47.94, 179.7, -42.94],
    width: 1536,
    height: 1536,
    tint: [1.0317, 1.0095, 0.9588],
  },
  {
    id: 'change-5',
    bbox: [-57.85268, 37.12132, -45.97932, 48.99468],
    width: 1536,
    height: 1536,
    tint: [1.0315, 1.0112, 0.9572],
  },
  // Wide level: the same mosaic over roughly 1200 km, so a focused view is still sharper than
  // the global atlas long before the fine crop above can cover the screen.
  {
    id: 'mare-ser-enitatis-wide',
    bbox: [-4.91234, 8.21108, 39.91234, 47.78892],
    width: 1536,
    height: 1536,
    tint: [1.0288, 1.0105, 0.9608],
  },
  {
    id: 'mare-tranquillitatis-wide',
    bbox: [11.3913, -11.28892, 51.4087, 28.28892],
    width: 1536,
    height: 1536,
    tint: [1.0197, 1.0118, 0.9685],
  },
  {
    id: 'mare-crisium-wide',
    bbox: [38.40689, -2.78892, 79.79311, 36.78892],
    width: 1536,
    height: 1536,
    tint: [1.0246, 1.0101, 0.9653],
  },
  {
    id: 'tycho-wide',
    bbox: [-38.55554, -63.09892, 15.83554, -23.52108],
    width: 1536,
    height: 1536,
    // Generated from the atlas itself, so it needs no WAC colour-cast correction.
    tint: [1, 1, 1],
  },
  {
    id: 'copernicus-wide',
    bbox: [-40.15116, -10.16892, -0.00884, 29.40892],
    width: 1536,
    height: 1536,
    tint: [1.021, 1.0114, 0.9676],
  },
  {
    id: 'aristarchus-wide',
    bbox: [-69.01158, 3.91108, -25.78842, 43.48892],
    width: 1536,
    height: 1536,
    tint: [1.0272, 1.0121, 0.9607],
  },
  {
    id: 'clavius-wide',
    bbox: [-52.16613, -78.18892, 23.36613, -38.61108],
    width: 1536,
    height: 1536,
    // Generated from the atlas itself, so it needs no WAC colour-cast correction.
    tint: [1, 1, 1],
  },
  {
    id: 'tsiolkovskiy-wide',
    bbox: [107.85965, -40.16892, 150.08035, -0.59108],
    width: 1536,
    height: 1536,
    tint: [1.0206, 1.0102, 0.9692],
  },
  {
    id: 'shackleton-wide',
    bbox: [-79.15567, -90, 79.15567, -70.11108],
    width: 1536,
    height: 1536,
    tint: [1.0187, 1.0091, 0.9722],
  },
  {
    id: 'apollo-11-wide',
    bbox: [3.64266, -19.10092, 43.22334, 20.47692],
    width: 1536,
    height: 1536,
    tint: [1.0172, 1.0114, 0.9715],
  },
  {
    id: 'apollo-17-wide',
    bbox: [9.68551, 0.40108, 51.85449, 39.97892],
    width: 1536,
    height: 1536,
    tint: [1.025, 1.0109, 0.9641],
  },
  {
    id: 'change-3-wide',
    bbox: [-47.07811, 24.33208, 8.05411, 63.90992],
    width: 1536,
    height: 1536,
    // Generated from the atlas itself, so it needs no WAC colour-cast correction.
    tint: [1, 1, 1],
  },
  {
    id: 'change-4-wide',
    bbox: [123.28966, -65.23292, 179.7, -25.65508],
    width: 1536,
    height: 1536,
    // Generated from the atlas itself, so it needs no WAC colour-cast correction.
    tint: [1, 1, 1],
  },
  {
    id: 'change-5-wide',
    bbox: [-78.99951, 23.26908, -24.83249, 62.84692],
    width: 1536,
    height: 1536,
    // Generated from the atlas itself, so it needs no WAC colour-cast correction.
    tint: [1, 1, 1],
  },
  // The smallest landing site humanity has left a rover at, and the longest rover traverse:
  // Lunokhod 2 drove about 39 km, so its wheel tracks are the sharpest thing in the demo.
  {
    id: 'luna-21',
    bbox: [24.515, 19.915, 36.385, 31.785],
    width: 1536,
    height: 1536,
    tint: [1.0312, 1.0005, 0.9035],
  },
  {
    id: 'luna-21-wide',
    bbox: [8.46081, 6.06108, 52.43919, 45.63892],
    width: 1536,
    height: 1536,
    tint: [1.0358, 0.9991, 0.9036],
  },
  // LROC Narrow Angle Camera tiers for the five landing sites with published mosaics. The first
  // of each pair carries the descent from the WAC crop; the second is framed at the mosaic's own
  // pixel scale and is what actually shows landers, rovers and wheel tracks.
  {
    id: 'apollo-11-nac',
    bbox: [23.37933, 0.61134, 23.50467, 0.73666],
    width: 4096,
    height: 4096,
    tint: [0.9983, 1.0036, 0.9696],
  },
  {
    id: 'apollo-11-nac-close',
    bbox: [23.40002, 0.64102, 23.46598, 0.70698],
    width: 4096,
    height: 4096,
    tint: [0.9983, 1.0036, 0.9696],
  },
  {
    id: 'apollo-17-nac',
    bbox: [30.56794, 20.00036, 30.97206, 20.37964],
    width: 4096,
    height: 4096,
    tint: [1.0099, 1.0017, 0.9543],
  },
  {
    id: 'apollo-17-nac-close',
    bbox: [30.73486, 20.15702, 30.80514, 20.22298],
    width: 4096,
    height: 4096,
    tint: [1.0099, 1.0017, 0.9543],
  },
  {
    id: 'change-4-nac',
    bbox: [177.36396, -45.60891, 177.83404, -45.27909],
    width: 4096,
    height: 4096,
    tint: [1.0209, 0.9990, 0.9488],
  },
  {
    id: 'change-4-nac-close',
    bbox: [177.48148, -45.52645, 177.71652, -45.36155],
    width: 3571,
    height: 3571,
    tint: [1.0209, 0.9990, 0.9488],
  },
  {
    id: 'change-5-nac',
    bbox: [-52.01079, 42.98874, -51.82121, 43.12726],
    width: 3500,
    height: 3500,
    tint: [1.0197, 0.9996, 0.9462],
  },
  {
    id: 'luna-21-nac',
    bbox: [30.15681, 25.58615, 30.74319, 26.11385],
    width: 4096,
    height: 4096,
    tint: [1.0312, 1.0005, 0.9035],
  },
  {
    id: 'luna-21-nac-close',
    bbox: [30.35288, 25.7626, 30.54712, 25.9374],
    width: 4096,
    height: 4096,
    tint: [1.0312, 1.0005, 0.9035],
  },
]

export function findSite(id: string): MoonSite | null {
  return MOON_SITES.find((site) => site.id === id) ?? null
}

/**
 * Bump strength for a crop, or null when the feature has no relief map. The number is a
 * multiplier on the globe's own bump scale; `siteBumps.ts` explains where it comes from.
 */
export function siteBumpScale(id: string): number | null {
  return SITE_BUMP_SCALE[id] ?? null
}

/** Absolute LOLA range used to move a crop's vertices onto the lunar terrain. */
export function siteRelief(id: string): SiteRelief | null {
  return SITE_RELIEF[id] ?? null
}

/**
 * Detail levels for a feature, coarsest first: the wide crop carries the view from a regional
 * altitude, the fine crop takes over as the camera closes in, and the NAC crops finish the
 * descent. Features with fewer tiers simply skip the missing ones.
 */
export function siteLevels(featureId: string): MoonSite[] {
  return TIER_ORDER.map((tier) => findSite(tier === 'fine' ? featureId : `${featureId}-${tier}`))
    .filter((site): site is MoonSite => site !== null)
}

/**
 * The crop that decides how close the camera may come. A feature with NAC imagery chains three
 * or four tiers, and the floor has to follow the deepest of them: the descent would otherwise
 * stall at the wide crop's limit, long before the NAC crops fade in. Features whose drill-down
 * stops at the WAC crops keep the wide crop's floor, which is what the demo has always used.
 */
export function siteFloorSite(featureId: string): MoonSite | null {
  const levels = siteLevels(featureId)
  const deepest = levels[levels.length - 1]
  if (!deepest) return null
  const tier = siteTier(deepest.id)
  return tier === 'nac' || tier === 'nac-close' ? deepest : levels[0]
}

/** Crops that make up a feature's drill-down, used by the tests to check the tier ordering. */
export function siteTiers(featureId: string): MoonSiteTier[] {
  return siteLevels(featureId).map((site) => siteTier(site.id))
}
