/**
 * Absolute LOLA elevation metadata for hotspot meshes, generated by
 * `tools/moon-textures/moon_textures.py relief`.
 *
 * Each lossless height texture spans `minKm .. minKm + rangeKm`, relative to the IAU lunar
 * reference sphere of radius 1737.4 km. `centerKm` lets the focused camera orbit the actual
 * ground instead of the mathematical sphere.
 */
export interface SiteRelief {
  minKm: number
  rangeKm: number
  centerKm: number
}

export const SITE_RELIEF: Record<string, SiteRelief> = {
  'apollo-11': { minKm: -4.320944, rangeKm: 5.927345, centerKm: -1.916633 },
  'apollo-11-nac': { minKm: -1.960469, rangeKm: 0.094169, centerKm: -1.915859 },
  'apollo-11-nac-close': { minKm: -1.932392, rangeKm: 0.047734, centerKm: -1.912451 },
  'apollo-11-wide': { minKm: -4.86307, rangeKm: 9.679675, centerKm: -1.917201 },
  'apollo-17': { minKm: -4.89374, rangeKm: 5.717561, centerKm: -2.629587 },
  'apollo-17-nac': { minKm: -2.924734, rangeKm: 1.678251, centerKm: -2.626527 },
  'apollo-17-nac-close': { minKm: -2.668327, rangeKm: 0.069032, centerKm: -2.626411 },
  'apollo-17-wide': { minKm: -4.91364, rangeKm: 8.254634, centerKm: -2.634465 },
  'aristarchus': { minKm: -3.303569, rangeKm: 4.819529, centerKm: -3.256285 },
  'aristarchus-wide': { minKm: -4.14746, rangeKm: 6.533564, centerKm: -3.246489 },
  'change-3': { minKm: -4.286002, rangeKm: 3.547541, centerKm: -2.634209 },
  'change-3-wide': { minKm: -5.02464, rangeKm: 7.872358, centerKm: -2.635011 },
  'change-4': { minKm: -6.7725, rangeKm: 5.073899, centerKm: -5.934366 },
  'change-4-nac': { minKm: -6.000984, rangeKm: 0.104437, centerKm: -5.92401 },
  'change-4-nac-close': { minKm: -5.96348, rangeKm: 0.06352, centerKm: -5.924012 },
  'change-4-wide': { minKm: -7.862274, rangeKm: 15.246014, centerKm: -2.195405 },
  'change-5': { minKm: -3.731681, rangeKm: 3.188299, centerKm: -2.544136 },
  'change-5-nac': { minKm: -2.560951, rangeKm: 0.028248, centerKm: -2.542042 },
  'change-5-wide': { minKm: -5.022457, rangeKm: 6.534507, centerKm: -2.546513 },
  'clavius': { minKm: -6.105066, rangeKm: 8.31474, centerKm: -2.933313 },
  'clavius-wide': { minKm: -6.091262, rangeKm: 12.130119, centerKm: -2.930244 },
  'copernicus': { minKm: -3.696753, rangeKm: 4.522, centerKm: -3.30678 },
  'copernicus-wide': { minKm: -4.588167, rangeKm: 7.757748, centerKm: -3.334157 },
  'luna-21': { minKm: -4.892761, rangeKm: 5.717318, centerKm: -2.672645 },
  'luna-21-nac': { minKm: -2.755893, rangeKm: 0.965617, centerKm: -2.672307 },
  'luna-21-nac-close': { minKm: -2.702643, rangeKm: 0.227574, centerKm: -2.672302 },
  'luna-21-wide': { minKm: -4.901247, rangeKm: 8.477107, centerKm: -2.673766 },
  'mare-crisium': { minKm: -5.534677, rangeKm: 8.884297, centerKm: -3.5929 },
  'mare-crisium-wide': { minKm: -5.534122, rangeKm: 8.892607, centerKm: -3.592445 },
  'mare-imbrium': { minKm: -5.002933, rangeKm: 8.411842, centerKm: -2.288589 },
  'mare-orientale': { minKm: -4.784351, rangeKm: 14.127674, centerKm: -2.751757 },
  'mare-ser-enitatis': { minKm: -6.577524, rangeKm: 10.184141, centerKm: -2.566321 },
  'mare-ser-enitatis-wide': { minKm: -6.560912, rangeKm: 10.162268, centerKm: -2.567924 },
  'mare-tranquillitatis': { minKm: -5.538022, rangeKm: 9.972719, centerKm: -0.913011 },
  'mare-tranquillitatis-wide': { minKm: -4.892179, rangeKm: 8.320708, centerKm: -0.912516 },
  'oceanus-procellarum': { minKm: -5.8445, rangeKm: 8.865627, centerKm: -2.151334 },
  'shackleton': { minKm: -5.499488, rangeKm: 11.706822, centerKm: -0.389274 },
  'shackleton-wide': { minKm: -5.818814, rangeKm: 12.843932, centerKm: 2.671405 },
  'south-pole-aitken': { minKm: -9.106495, rangeKm: 15.586694, centerKm: -5.154143 },
  'tsiolkovskiy': { minKm: -3.498737, rangeKm: 9.600615, centerKm: -1.750747 },
  'tsiolkovskiy-wide': { minKm: -4.653095, rangeKm: 12.174656, centerKm: -1.753122 },
  'tycho': { minKm: -3.539706, rangeKm: 5.369267, centerKm: -1.535737 },
  'tycho-wide': { minKm: -6.065158, rangeKm: 8.976897, centerKm: -1.401904 },
}
