/**
 * Absolute LOLA elevation metadata for hotspot meshes, generated by
 * `tools/moon-textures/moon_textures.py relief`.
 *
 * Each lossless height texture spans `minKm .. minKm + rangeKm`, relative to the IAU lunar
 * reference sphere of radius 1737.4 km. `centerKm` lets the focused camera orbit the actual
 * ground instead of the mathematical sphere.
 *
 * `liftKm` raises the crop above the globe it floats on. The globe's own displacement comes
 * from the coarse 16 pixel-per-degree atlas DEM, which smooths large craters away; inside one
 * of those, the atlas sphere reads up to a kilometre higher than the detailed crop DEM and
 * would rise through the crop, showing the blurry atlas in place of the crater floor. The
 * generator measures that disagreement over each crop and stores the clearance here.
 */
export interface SiteRelief {
  minKm: number
  rangeKm: number
  centerKm: number
  liftKm: number
}

export const SITE_RELIEF: Record<string, SiteRelief> = {
  'apollo-11': { minKm: -4.320944, rangeKm: 5.927345, centerKm: -1.916633, liftKm: 2.431629 },
  'apollo-11-nac': { minKm: -1.960469, rangeKm: 0.094169, centerKm: -1.915859, liftKm: 0.158901 },
  'apollo-11-nac-close': { minKm: -1.932392, rangeKm: 0.047734, centerKm: -1.912451, liftKm: 0.130823 },
  'apollo-11-wide': { minKm: -4.86307, rangeKm: 9.679675, centerKm: -1.917201, liftKm: 1.046442 },
  'apollo-17': { minKm: -4.89374, rangeKm: 5.717561, centerKm: -2.629587, liftKm: 2.382292 },
  'apollo-17-nac': { minKm: -2.924734, rangeKm: 1.678251, centerKm: -2.626527, liftKm: 0.424612 },
  'apollo-17-nac-close': { minKm: -2.668327, rangeKm: 0.069032, centerKm: -2.626411, liftKm: 0.165835 },
  'apollo-17-wide': { minKm: -4.91364, rangeKm: 8.254634, centerKm: -2.634465, liftKm: 1.023295 },
  'aristarchus': { minKm: -3.303569, rangeKm: 4.819529, centerKm: -3.256285, liftKm: 2.202954 },
  'aristarchus-wide': { minKm: -4.14746, rangeKm: 6.533564, centerKm: -3.246489, liftKm: 1.103672 },
  'change-3': { minKm: -4.286002, rangeKm: 3.547541, centerKm: -2.634209, liftKm: 1.821848 },
  'change-3-wide': { minKm: -5.02464, rangeKm: 7.872358, centerKm: -2.635011, liftKm: 0.861443 },
  'change-4': { minKm: -6.7725, rangeKm: 5.073899, centerKm: -5.934366, liftKm: 1.572939 },
  'change-4-nac': { minKm: -6.000984, rangeKm: 0.104437, centerKm: -5.92401, liftKm: 0.175886 },
  'change-4-nac-close': { minKm: -5.96348, rangeKm: 0.06352, centerKm: -5.924012, liftKm: 0.138382 },
  'change-4-wide': { minKm: -7.862274, rangeKm: 15.246014, centerKm: -2.195405, liftKm: 0.857015 },
  'change-5': { minKm: -3.731681, rangeKm: 3.188299, centerKm: -2.544136, liftKm: 1.497816 },
  'change-5-nac': { minKm: -2.560951, rangeKm: 0.028248, centerKm: -2.542042, liftKm: 0.158241 },
  'change-5-wide': { minKm: -5.022457, rangeKm: 6.534507, centerKm: -2.546513, liftKm: 0.925699 },
  'clavius': { minKm: -6.105066, rangeKm: 8.31474, centerKm: -2.933313, liftKm: 2.595624 },
  'clavius-wide': { minKm: -6.091262, rangeKm: 12.130119, centerKm: -2.930244, liftKm: 2.90875 },
  'copernicus': { minKm: -3.696753, rangeKm: 4.522, centerKm: -3.30678, liftKm: 1.883927 },
  'copernicus-wide': { minKm: -4.588167, rangeKm: 7.757748, centerKm: -3.334157, liftKm: 2.716311 },
  'luna-21': { minKm: -4.892761, rangeKm: 5.717318, centerKm: -2.672645, liftKm: 2.382452 },
  'luna-21-nac': { minKm: -2.755893, rangeKm: 0.965617, centerKm: -2.672307, liftKm: 0.412476 },
  'luna-21-nac-close': { minKm: -2.702643, rangeKm: 0.227574, centerKm: -2.672302, liftKm: 0.179289 },
  'luna-21-wide': { minKm: -4.901247, rangeKm: 8.477107, centerKm: -2.673766, liftKm: 0.989834 },
  'mare-crisium': { minKm: -5.534677, rangeKm: 8.884297, centerKm: -3.5929, liftKm: 3.758358 },
  'mare-crisium-wide': { minKm: -5.534122, rangeKm: 8.892607, centerKm: -3.592445, liftKm: 1.088447 },
  'mare-imbrium': { minKm: -5.002933, rangeKm: 8.411842, centerKm: -2.288589, liftKm: 3.135423 },
  'mare-orientale': { minKm: -4.784351, rangeKm: 14.127674, centerKm: -2.751757, liftKm: 3.42032 },
  'mare-ser-enitatis': { minKm: -6.577524, rangeKm: 10.184141, centerKm: -2.566321, liftKm: 3.120161 },
  'mare-ser-enitatis-wide': { minKm: -6.560912, rangeKm: 10.162268, centerKm: -2.567924, liftKm: 0.915193 },
  'mare-tranquillitatis': { minKm: -5.538022, rangeKm: 9.972719, centerKm: -0.913011, liftKm: 3.173796 },
  'mare-tranquillitatis-wide': { minKm: -4.892179, rangeKm: 8.320708, centerKm: -0.912516, liftKm: 1.07081 },
  'oceanus-procellarum': { minKm: -5.8445, rangeKm: 8.865627, centerKm: -2.151334, liftKm: 3.017959 },
  'shackleton': { minKm: -5.499488, rangeKm: 11.706822, centerKm: -0.389274, liftKm: 5.39373 },
  'shackleton-wide': { minKm: -5.818814, rangeKm: 12.843932, centerKm: 2.671405, liftKm: 0.755477 },
  'south-pole-aitken': { minKm: -9.106495, rangeKm: 15.586694, centerKm: -5.154143, liftKm: 3.506476 },
  'tsiolkovskiy': { minKm: -3.498737, rangeKm: 9.600615, centerKm: -1.750747, liftKm: 2.844813 },
  'tsiolkovskiy-wide': { minKm: -4.653095, rangeKm: 12.174656, centerKm: -1.753122, liftKm: 0.982841 },
  'tycho': { minKm: -3.539706, rangeKm: 5.369267, centerKm: -1.535737, liftKm: 2.053956 },
  'tycho-wide': { minKm: -6.065158, rangeKm: 8.976897, centerKm: -1.401904, liftKm: 2.809959 },
}
