/**
 * Bump strength for every hotspot crop, generated by `tools/moon-textures/moon_textures.py`.
 *
 * The scene lights the globe with the LOLA height map as a bump map: an 8-bit grey image whose
 * values run linearly over the Moon's -9 km .. +10 km range, with a bump scale of 1.2. A crop's
 * bump map uses the same convention but stretches its own local height range over the full 8-bit
 * scale, because a hundred kilometres of terrain would otherwise occupy a handful of levels. The
 * numbers below are a multiple of the globe's own scale, sized so a patch gets the same relief
 * strength as the ground it covers; the tool derives them from each crop's DEM.
 *
 * Features with no entry keep their baked shading: the LROC NAC tiers are metre-scale photographs
 * of landing sites, and no DEM that resolves them exists to relight them with.
 */
export const SITE_BUMP_SCALE: Record<string, number> = {
  'apollo-11': 0.9359,
  'apollo-11-wide': 1.52837,
  'apollo-17': 0.90277,
  'change-3': 0.56014,
  'change-3-wide': 1.243,
  'change-4': 0.80114,
  'change-4-wide': 2.40727,
  'change-5': 0.50342,
  'change-5-wide': 1.03176,
  'clavius': 1.31285,
  'clavius-wide': 1.91528,
  'copernicus': 0.714,
  'luna-21': 0.90273,
  'mare-crisium': 1.40278,
  'mare-imbrium': 1.32819,
  'mare-orientale': 2.23069,
  'mare-ser-enitatis': 1.60802,
  'mare-tranquillitatis': 1.57464,
  'oceanus-procellarum': 1.39984,
  'south-pole-aitken': 2.46106,
  'tsiolkovskiy': 1.51589,
  'tycho': 0.84778,
  'tycho-wide': 1.4174,
}
