"""Build the reviewed refractor classification GLB from telescope_refractor.glb.

The source is never modified. This builder:
  1. verifies the source SHA-256, so the reviewed mapping cannot silently drift;
  2. bakes every parent transform and splits each material primitive into welded
     connected fragments;
  3. assigns each fragment a reviewed partId together with the measured evidence;
  4. keeps the source optical elements in their functional groups and adds closed
     teaching surfaces for the ray-path lesson;
  5. writes the calibrated optical frame and traced ray paths into the scene extras;
  6. reports triangle counts per source primitive so the split can be verified.

Run: .cache/venv-tools/Scripts/python.exe tools/build-refractor-model.py
"""
import hashlib
import json
import runpy
import struct
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'frontend/public/models/telescope_refractor.glb'
TARGET = ROOT / 'frontend/public/models/telescope_refractor_classified.glb'
CACHE = ROOT / '.cache/refractor-audit'
SOURCE_HASH = 'ee85606fdecd74ebb05bbca88b6787864382870e25db55a3220d10a2c4002a09'

if hashlib.sha256(SOURCE.read_bytes()).hexdigest() != SOURCE_HASH:
    raise SystemExit('Source GLB changed. Re-audit geometry and mapping before rebuilding.')

audit = runpy.run_path(str(ROOT / 'tools/audit-refractor.py'))
source, read, matrix, components = [audit[k] for k in ['doc', 'accessor', 'matrix', 'components']]
instances = audit['instances']

# ----------------------------------------------------------------------------------
# Reviewed classification. Values record the measured evidence, never a node name.
# ----------------------------------------------------------------------------------
EVIDENCE = {
    'opticalTube': 'the unique 643 mm coaxial shell; its enlarged objective end surrounds the objective '
                   'and forms the sun shade, while its narrow viewing end meets the focuser',
    'objectiveCell': 'a stepped coaxial collar immediately surrounding the objective pair at the '
                     'large-aperture objective end of the main tube',
    'objectiveLens': 'two 108.8 mm coaxial convex optical blanks directly inside the large objective '
                     'cell at the sky-facing end of the tube',
    'tubeRings': 'two large split rings around the main tube together with the curved saddle, longitudinal '
                 'dovetail plate above the equatorial head',
    'fasteners': 'the reviewed screws, nut-like thumb fasteners, clamping knobs and locking controls '
                 'distributed across the finder, focuser, tube rings, mount, counterweight and tripod',
    'finderScope': 'a complete small optical train 98..147 mm from and parallel to the main axis, above the '
                   'tube: two lenses, barrel, mounting shoe, bracket and three radial alignment screws',
    'focuser': 'the rear viewing-end assembly: coaxial drawtube and body plus paired side wheels and '
               'controls, all immediately before the diagonal',
    'diagonal': 'the angled rear housing between drawtube and eyepiece, including its oblique reflecting '
                'surface; the coaxial rear tube remains part of the focuser assembly',
    'eyepieceLensGroup': 'the small convex optical element and coaxial barrel at the viewing end of the '
                         'diagonal, following the side optical port',
    'mount': 'the intersecting equatorial-axis castings and their locks and adjustment controls directly '
             'below the tube saddle and above the tripod',
    'counterweight': 'the circular weight opposite the telescope, the long shaft joining it to the '
                     'declination axis and the shaft-end lock',
    'tripod': 'three two-section ground legs with feet and clamps, plus three spreader rods, their '
              'connectors and the central polygonal hub',
}

# The mapping is generated by tools/refractor-classify.py; the builder reads it rather than
# restating it, so the classified GLB cannot drift out of step with the reviewed source fragments.
PART_OF = json.loads((Path(__file__).resolve().parents[1] / '.cache/refractor-audit/part-of.json')
                     .read_text())
if not PART_OF:
    raise SystemExit('run tools/refractor-classify.py first: it writes the reviewed fragment mapping')
FASTENER_OF = json.loads((CACHE / 'fastener-of.json').read_text())

NAMES = {
    'opticalTube': 'OpticalTubeAndSunShade', 'objectiveCell': 'ObjectiveCell',
    'objectiveLens': 'ObjectiveLens', 'tubeRings': 'TubeRingsAndDovetail',
    'fasteners': 'Fasteners',
    'finderScope': 'FinderScope', 'focuser': 'Focuser', 'diagonal': 'StarDiagonal',
    'eyepieceLensGroup': 'Eyepiece', 'mount': 'EquatorialMount',
    'counterweight': 'CounterweightAndShaft', 'tripod': 'TripodAndSpreader',
}

# ----------------------------------------------------------------------------------
# Optical calibration derived afresh from SOURCE vertices, never a cached axis sign.
# ----------------------------------------------------------------------------------
fragments = {}
for inst in instances:
    for ci, faces in enumerate(components(inst['tri'], return_ids=True)):
        tag = f"n{inst['node']}-m{inst['mesh']}-p{inst['prim']}:c{ci}"
        fragments[tag] = inst['tri'][faces]


def unique_points(tag):
    return np.unique(fragments[tag].reshape(-1, 3), axis=0)


objective_tags = ['n12-m6-p0:c1', 'n12-m6-p0:c0']
eyepiece_tag = 'n12-m6-p0:c3'  # the small on-axis viewing lens; the side port is separate
front_pts = unique_points(objective_tags[0])
eye_pts = unique_points(eyepiece_tag)
_, vectors = np.linalg.eigh(np.cov(front_pts.T))
axis = vectors[:, 0]
if axis @ (eye_pts.mean(0) - front_pts.mean(0)) < 0:
    axis = -axis
up = np.array([0., 1., 0.])
up -= axis * (up @ axis)
up /= np.linalg.norm(up)
right = np.cross(axis, up)
O = front_pts.mean(0)
# All subsequent coordinates, generated surfaces and exported metadata use this ONE frame.
EXPORT_AXIS, EXPORT_UP, EXPORT_RIGHT = axis, up, right


def to_optical(points):
    return (np.atleast_2d(points) - O) @ np.array([axis, up, right]).T


def to_world(s, u, v):
    return np.outer(s, axis) + np.outer(u, up) + np.outer(v, right) + O


def landmark(tag):
    points = to_optical(unique_points(tag))
    return {'source': tag, 's': float((points[:, 0].min() + points[:, 0].max()) / 2),
            'front': float(points[:, 0].min()), 'back': float(points[:, 0].max()),
            'radius': float(np.linalg.norm(points[:, 1:], axis=1).max()),
            'center': to_world([(points[:, 0].min() + points[:, 0].max()) / 2], [0], [0])[0].tolist()}


landmarks = [landmark(tag) for tag in objective_tags]
eye_landmark = landmark(eyepiece_tag)
assert landmarks[0]['s'] < landmarks[1]['s'] < eye_landmark['s']
assert landmarks[0]['radius'] > 4 * eye_landmark['radius']
LENS_FRONT = landmarks[0]['s']
LENS_BACK = landmarks[1]['s']
EYEPIECE_FRONT = eye_landmark['s']
EYEPIECE_BACK = EYEPIECE_FRONT + .001
EYEPIECE_F = .030
FOCUS_S = EYEPIECE_FRONT - EYEPIECE_F
TRACED_EFL = FOCUS_S - LENS_BACK
APERTURE = .036                         # representative 72 mm bundle within the source objective
LENS_SEMI = .050
EYE_SEMI = .0095
END_S = EYEPIECE_BACK + .100
FIELD_ANGLES = [0., .006, -.006]
APERTURE_FRACTIONS = [-1., -.6, -.2, .2, .6, 1.]


def build_ray(aperture_frac, field_angle):
    # Paraxial equivalent thin lenses. Off-axis incident rays have a nonzero field slope;
    # rays of one field meet one image point and leave the eye lens parallel to each other.
    incoming_slope = np.tan(field_angle)
    entry_y = APERTURE * aperture_frac
    rear_y = entry_y + incoming_slope * (LENS_BACK - LENS_FRONT)
    image_height = incoming_slope * TRACED_EFL
    converging_slope = incoming_slope - rear_y / TRACED_EFL
    eyepiece_y = image_height + converging_slope * EYEPIECE_F
    exit_slope = converging_slope - eyepiece_y / EYEPIECE_F
    rear_eye_y = eyepiece_y + exit_slope * (EYEPIECE_BACK - EYEPIECE_FRONT)
    return {'field': field_angle, 'apertureFrac': aperture_frac, 'exitSlope': exit_slope,
            'focusY': image_height, 'focusCrossing': FOCUS_S,
            'points': [[LENS_FRONT, entry_y], [LENS_BACK, rear_y], [FOCUS_S, image_height],
                       [EYEPIECE_FRONT, eyepiece_y], [EYEPIECE_BACK, rear_eye_y],
                       [END_S, rear_eye_y + exit_slope * (END_S - EYEPIECE_BACK)]]}


rays = [build_ray(f, angle) for angle in FIELD_ANGLES for f in APERTURE_FRACTIONS]
# Slice the actual shell triangles. Sparse vertex bins previously applied the rear throat's small
# radius to the objective end and missed most of the tube. Triangle-plane intersections cover it.
tube_tri = to_optical(fragments['n4-m2-p0:c1'].reshape(-1, 3)).reshape(-1, 3, 3)
TUBE_FRONT, TUBE_REAR = float(tube_tri[:, :, 0].min()), float(tube_tri[:, :, 0].max())
planes = np.linspace(TUBE_FRONT + 1e-6, TUBE_REAR - 1e-6, 180)
bore_samples = []
for s in planes:
    intersections = []
    for i, j in [(0, 1), (1, 2), (2, 0)]:
        a, b = tube_tri[:, i], tube_tri[:, j]
        delta = b[:, 0] - a[:, 0]
        valid = (np.abs(delta) > 1e-10) & ((a[:, 0] - s) * (b[:, 0] - s) <= 0)
        t = (s - a[valid, 0]) / delta[valid]
        intersections.extend(a[valid, 1:] + t[:, None] * (b[valid, 1:] - a[valid, 1:]))
    if len(intersections):
        bore_samples.append([float(s), float(np.linalg.norm(intersections, axis=1).min())])
assert len(bore_samples) == len(planes)


def height_at(ray, s):
    points = ray['points']
    if s < points[0][0]:
        return points[0][1] + np.tan(ray['field']) * (s - points[0][0])
    return float(np.interp(s, [p[0] for p in points], [p[1] for p in points]))


wall_margin = min(radius - abs(height_at(ray, s)) for ray in rays for s, radius in bore_samples)
if wall_margin <= 0:
    raise SystemExit(f'Ray intersects source tube shell: {wall_margin * 1000:.3f} mm clearance')
if max(abs(r['points'][3][1]) for r in rays) >= EYE_SEMI:
    raise SystemExit('Ray misses the source eyepiece')
print(f'  source-anchored axis: {axis.round(6).tolist()}')
print(f'  objective planes {LENS_FRONT*1000:.2f}/{LENS_BACK*1000:.2f} mm; '
      f'focus {FOCUS_S*1000:.2f} mm; eyepiece {EYEPIECE_FRONT*1000:.2f} mm')
print(f'  {len(rays)} rays, sampled tube clearance {wall_margin*1000:.2f} mm')


# Appearance reviewed against the reference photograph supplied with the task.
#
# The source model has no textures, no images and no text geometry at all, so there is nothing to
# strip: the reference's "VIXIX" badge, the small blue discs and the tripod-leg lettering simply do
# not exist in this geometry and are deliberately NOT recreated here. What is matched is the material
# scheme: an off-white tube, finder and mount on near-black optics, focuser and
# spreaders, with a white counterweight and metallic silver counterweight shaft.
# ----------------------------------------------------------------------------------
APPEARANCE = {
    # part           : (base colour,      metallic, roughness)
    # The reference finish is a clean white instrument with black optical hardware.
    # Keep the palette neutral so the model does not acquire a blue cast on the light stage.
    'opticalTube': (.965, .965, .955, .02, .38),
    'objectiveCell': (.945, .945, .935, .06, .34),
    'tubeRings': (.905, .905, .895, .10, .40),
    'focuser': (.035, .038, .045, .55, .28),
    'finderScope': (.950, .950, .940, .04, .38),
    'diagonal': (.025, .028, .035, .58, .24),
    'mount': (.925, .925, .915, .08, .38),
    # The weight is white like the reference body; the separate shaft material below is metallic.
    'counterweight': (.950, .950, .940, .08, .38),
    'tripod': (.955, .955, .945, .03, .40),
}

# Part -> the GLB material index that carries its appearance.
MATERIAL_OF = {}
for part in list(APPEARANCE) + ['objectiveLens', 'eyepieceLensGroup']:
    MATERIAL_OF[part] = len(MATERIAL_OF)
MATERIAL_OF['counterweightRod'] = len(MATERIAL_OF)
MATERIAL_OF['blackHardware'] = len(MATERIAL_OF)
MATERIAL_OF['finderGlass'] = len(MATERIAL_OF)
MATERIAL_OF['focuserWhite'] = len(MATERIAL_OF)

# Source component roles that must not be inferred from their parent partId. In particular, the
# eyepiece barrel shares a functional group with the eyepiece glass, but it is opaque black metal.
COMPONENT_ROLE = {
    'n12-m6-p0:c2': 'finderLensRear',
    'n12-m6-p0:c3': 'eyepieceLens',
    'n12-m6-p0:c5': 'finderLensFront',
    'n14-m7-p0:c4': 'eyepieceBarrel',
    'n14-m7-p0:c3': 'finderRearBarrel',
    'n14-m7-p0:c7': 'finderFrontBarrel',
}
BLACK_COMPONENTS = {
    'n14-m7-p0:c4', 'n14-m7-p0:c3', 'n14-m7-p0:c7',
    'n14-m7-p0:c0', 'n14-m7-p0:c1', 'n14-m7-p0:c2',
}
FINDER_GLASS_COMPONENTS = {'n12-m6-p0:c2', 'n12-m6-p0:c5'}
WHITE_COMPONENTS = {'n4-m2-p0:c17'}


def material_for(part):
    """The GLB material definition for one reviewed category, plus the teaching optics."""
    if part == 'objectiveLens':
        # The reference shows the objective aperture as a dark optical opening. Keep it
        # translucent enough for the ray lesson while retaining that black appearance.
        return {'name': 'teachingObjectiveGlass',
                'pbrMetallicRoughness': {'baseColorFactor': [.035, .115, .135, .70],
                                         'metallicFactor': 0.0, 'roughnessFactor': .07},
                'alphaMode': 'BLEND', 'doubleSided': True}
    if part == 'eyepieceLensGroup':
        return {'name': 'teachingEyepieceGlass',
                'pbrMetallicRoughness': {'baseColorFactor': [.045, .135, .155, .74],
                                         'metallicFactor': 0.0, 'roughnessFactor': .05},
                'alphaMode': 'BLEND', 'doubleSided': True}
    if part == 'finderGlass':
        return {'name': 'refractorFinderGlass',
                'pbrMetallicRoughness': {'baseColorFactor': [.055, .165, .180, .68],
                                         'metallicFactor': 0.0, 'roughnessFactor': .08},
                'alphaMode': 'BLEND', 'doubleSided': True}
    if part == 'focuserWhite':
        return {'name': 'refractorFocuserWhiteFinish',
                'pbrMetallicRoughness': {'baseColorFactor': [.965, .965, .950, 1.0],
                                         'metallicFactor': .03, 'roughnessFactor': .34}}
    if part == 'counterweightRod':
        return {'name': 'refractorCounterweightRodMetal',
                'pbrMetallicRoughness': {'baseColorFactor': [.52, .55, .58, 1.0],
                                         'metallicFactor': .88, 'roughnessFactor': .22}}
    if part == 'blackHardware':
        return {'name': 'refractorBlackHardware',
                'pbrMetallicRoughness': {'baseColorFactor': [.018, .020, .025, 1.0],
                                         'metallicFactor': .42, 'roughnessFactor': .28}}
    r, g, b, metallic, roughness = APPEARANCE[part]
    return {'name': f'refractor{part[0].upper()}{part[1:]}Finish',
            'pbrMetallicRoughness': {'baseColorFactor': [r, g, b, 1.0],
                                     'metallicFactor': metallic, 'roughnessFactor': roughness}}


# ----------------------------------------------------------------------------------
# GLB assembly
# ----------------------------------------------------------------------------------
output = {'asset': {'version': '2.0', 'generator': 'Astro geometry-reviewed refractor builder'},
          'scene': 0, 'scenes': [{'nodes': []}], 'nodes': [], 'meshes': [],
          'materials': [material_for(part) for part in MATERIAL_OF],
          'buffers': [{'byteLength': 0}], 'bufferViews': [], 'accessors': []}
binary = bytearray()
report = []


def add_accessor(values):
    values = np.asarray(values, dtype='<f4')
    while len(binary) % 4:
        binary.append(0)
    offset = len(binary)
    binary.extend(values.tobytes())
    view = len(output['bufferViews'])
    output['bufferViews'].append({'buffer': 0, 'byteOffset': offset, 'byteLength': values.nbytes,
                                  'target': 34962})
    aid = len(output['accessors'])
    output['accessors'].append({'bufferView': view, 'componentType': 5126, 'count': len(values),
                                'type': 'VEC3', 'min': values.min(axis=0).tolist(),
                                'max': values.max(axis=0).tolist()})
    return aid


def add_solid(name, positions, normals, material, extras):
    mesh_id = len(output['meshes'])
    output['meshes'].append({'name': name, 'primitives': [{
        'attributes': {'POSITION': add_accessor(positions), 'NORMAL': add_accessor(normals)},
        'material': material}]})
    node_id = len(output['nodes'])
    output['nodes'].append({'name': name, 'mesh': mesh_id, 'extras': extras})
    output['scenes'][0]['nodes'].append(node_id)
    report.append({'name': name, 'part': extras['partId'], 'triangles': len(positions) // 3,
                   'sourceNode': extras.get('sourceNode'),
                   'sourcePrimitive': extras.get('sourcePrimitive')})
    return node_id


for inst in instances:
    ni, mid, pi = inst['node'], inst['mesh'], inst['prim']
    primitive = source['meshes'][mid]['primitives'][pi]
    m = matrix(ni)
    positions = read(primitive['attributes']['POSITION'])
    ids = read(primitive['indices']).flatten() if 'indices' in primitive else np.arange(len(positions))
    # The source is in metres and the optical frame, the rays and the calibration are all in
    # metres too, so the baked geometry is written in metres. Scaling here instead would put
    # the geometry and the calibration in different units inside one file.
    world = (np.c_[positions, np.ones(len(positions))] @ m.T)[:, :3]
    normals = read(primitive['attributes']['NORMAL']) @ np.linalg.inv(m[:3, :3])
    normals /= np.maximum(np.linalg.norm(normals, axis=1)[:, None], 1e-16)
    triangles = world[ids.reshape(-1, 3)]
    for ci, faces in enumerate(components(triangles, return_ids=True)):
        tag = f'n{ni}-m{mid}-p{pi}:c{ci}'
        part = PART_OF.get(tag)
        if part is None:
            raise SystemExit(f'unmapped fragment {tag} ({len(faces)} faces)')
        vertex_ids = ids.reshape(-1, 3)[faces].flatten()
        material_part = ('counterweightRod' if tag == 'n10-m5-p0:c10'
                         else 'blackHardware' if tag in FASTENER_OF or tag in BLACK_COMPONENTS
                         else 'finderGlass' if tag in FINDER_GLASS_COMPONENTS
                         else 'focuserWhite' if tag in WHITE_COMPONENTS
                         else part)
        extras = {
            'partId': part, 'sourceNode': ni, 'sourceMesh': mid, 'sourcePrimitive': pi,
            'sourceComponent': ci,
            'confidence': 'reviewed',
            'evidence': EVIDENCE[part], 'geometrySource': 'source',
        }
        if tag in COMPONENT_ROLE:
            extras['componentRole'] = COMPONENT_ROLE[tag]
        if tag in FASTENER_OF:
            extras['hardwareClass'] = 'fastener'
            extras['fastenerType'] = FASTENER_OF[tag]
        add_solid(f'{NAMES[part]}_n{ni}_p{pi}_c{ci}', world[vertex_ids], normals[vertex_ids],
                  MATERIAL_OF[material_part], extras)
print(f'wrote {len(report)} reviewed fragments')


def build_lens(part, name, center, semi, half_thickness):
    # Closed biconvex teaching profile with shared rim coordinates and no duplicated pole faces.
    segments, rings = 64, 12
    profiles = []
    for side in [-1, 1]:
        profiles.append([(center + side * half_thickness, 0., 0.)])
        for ring in range(1, rings + 1):
            radius = semi * ring / rings
            half = .0004 + (half_thickness - .0004) * (1 - (radius / semi)**2)
            profiles[-1].extend((center + side * half, radius*np.cos(j*2*np.pi/segments),
                                radius*np.sin(j*2*np.pi/segments)) for j in range(segments))
    positions = np.array(profiles[0] + profiles[1])
    count = len(profiles[0])
    faces = []
    for side in range(2):
        offset = side * count
        cap = []
        for j in range(segments):
            cap.append([offset, offset+1+j, offset+1+(j+1)%segments])
        for ring in range(1, rings):
            for j in range(segments):
                a = offset+1+(ring-1)*segments+j
                b = offset+1+(ring-1)*segments+(j+1)%segments
                c, d = a+segments, b+segments
                cap.extend([[a,c,d],[a,d,b]])
        faces.extend([f[::-1] if side == 0 else f for f in cap])
    start = 1+(rings-1)*segments
    for j in range(segments):
        a, b = start+j, start+(j+1)%segments
        faces.extend([[a,b,b+count],[a,b+count,a+count]])
    world = to_world(positions[:,0], positions[:,1], positions[:,2])
    triangles = world[np.array(faces)]
    normals = np.cross(triangles[:,1]-triangles[:,0], triangles[:,2]-triangles[:,0])
    normals /= np.linalg.norm(normals,axis=1)[:,None]
    add_solid(name, triangles.reshape(-1,3), np.repeat(normals,3,axis=0), MATERIAL_OF[part], {
        'partId': part, 'geometrySource': 'teaching-additive', 'opticalGeometry': True,
        'closedSolid': True, 'diameter': 2*semi, 'confidence': 'added', 'evidence': EVIDENCE[part],
        'note': 'Display surface anchored to the source lens; paraxial equivalent thin-lens lesson.'})


build_lens('objectiveLens', 'TeachingObjectiveFront', LENS_FRONT, LENS_SEMI, .003)
build_lens('objectiveLens', 'TeachingObjectiveRear', LENS_BACK, LENS_SEMI, .003)
build_lens('eyepieceLensGroup', 'TeachingEyepiece', EYEPIECE_FRONT, EYE_SEMI, .001)
frame_matrix = np.eye(4)
frame_matrix[:3, :3] = np.array([axis, up, right]).T
frame_matrix[:3, 3] = O
metadata = {
    'opticalRevision': 9,
    'sourceLandmarks': {'objective': landmarks, 'eyepiece': eye_landmark},
    'opticalFrame': frame_matrix.flatten(order='F').tolist(),
    'tubeObjectiveEndS': TUBE_FRONT, 'tubeEyepieceEndS': TUBE_REAR,
    'minBoreRadius': min(p[1] for p in bore_samples), 'tubeRadiusMax': float(np.linalg.norm(tube_tri[:,:,1:],axis=2).max()),
    'boreSamples': bore_samples,
    'objectiveFrontS': LENS_FRONT, 'objectiveS': LENS_BACK,
    'objectiveLensDiameter': 2*LENS_SEMI, 'objectiveAperture': 2*APERTURE,
    'objectiveClearStopRadius': landmarks[0]['radius'], 'cellBoreRadius': landmarks[0]['radius'],
    'focalLength': TRACED_EFL, 'focalRatio': TRACED_EFL/(2*APERTURE), 'focusS': FOCUS_S,
    'eyepieceElementRadius': EYE_SEMI, 'eyepieceFrontS': EYEPIECE_FRONT, 'eyepieceBackS': EYEPIECE_BACK,
    'exitPupilRadius': APERTURE*EYEPIECE_F/TRACED_EFL,
    'eyepieceFocalLength': EYEPIECE_F, 'magnification': TRACED_EFL/EYEPIECE_F,
    'fieldAngleRad': max(FIELD_ANGLES), 'rays': rays,
    'disclosure': 'Teaching approximation: paraxial equivalent thin lenses anchored to source glass. '
                  'The on-axis viewing port is used; the side port is not part of this straight-through lesson.',
}
output['scenes'][0]['extras'] = metadata
output['buffers'][0]['byteLength'] = len(binary)

js = json.dumps(output, separators=(',', ':')).encode()
js += b' ' * ((-len(js)) % 4)
binary += b'\0' * ((-len(binary)) % 4)
TARGET.write_bytes(struct.pack('<III', 0x46546C67, 2, 28 + len(js) + len(binary))
                   + struct.pack('<II', len(js), 0x4E4F534A) + js
                   + struct.pack('<II', len(binary), 0x004E4942) + bytes(binary))
(CACHE / 'classification.json').write_text(json.dumps(report, indent=2))
(CACHE / 'metadata.json').write_text(json.dumps(metadata, indent=2))
print('BUILT', TARGET, TARGET.stat().st_size, 'bytes,', len(report), 'nodes')
